export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const EDIT_IMAGE_LAYOUT = 'EDIT_IMAGE_LAYOUT';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const CLICK_MENU = 'CLICK_MENU';
export const SHOW_LAYOUT_OVERLAY = 'SHOW_LAYOUT_OVERLAY';
