/**
 * Created by Chris Ho on 6/30/2016.
 */
export const  LEFT_RIGHT = 'LEFT_RIGHT';
export const UP_DOWN = 'UP_DOWN';
export const LARGE = 'LARGE';
export const MEDIUM = 'MEDIUM';
export const FULL = 'FULL';
export const FULL_SECTION = 'FULL_SECTION';
export const LANDSCAPE = 'LAND_CAPE';
export const PORTRAIT = 'PORTRAIT';
export const LAYOUT_ID_16x9_FULL = 'LAYOUT_ID_16x9_FULL';
export const LAYOUT_ID_16x9 = 'LAYOUT_ID_16x9';
export const LAYOUT_ID_16x9_TWO_UP_DOWN = 'LAYOUT_ID_16x9_TWO_UP_DOWN';
export const LAYOUT_ID_3x4_ONE_LANDSCAPE_BIG = 'LAYOUT_ID_3x4_ONE_LANDSCAPE_BIG';
export const LAYOUT_ID_3x4_ONE_PORTRAIT = 'LAYOUT_ID_3x4_ONE_PORTRAIT';
export const LAYOUT_ID_3x4_ONE_LANDSCAPE_MEDIUM = 'LAYOUT_ID_3x4_ONE_LANDSCAPE_MEDIUM';
export const LAYOUT_ID_3x4_TWO_PORTRAIT = 'LAYOUT_ID_3x4_TWO_PORTRAIT';
export const LAYOUT_ID_3x4_TWO_LANDSCAPE = 'LAYOUT_ID_3x4_TWO_LANDSCAPE';
export const LAYOUT_ID_2x3_ONE_LANDSCAPE_BIG = 'LAYOUT_ID_2x3_ONE_LANDSCAPE_BIG';
export const LAYOUT_ID_2x3_ONE_LANDSCAPE_MEDIUM = 'LAYOUT_ID_2x3_ONE_LANDSCAPE_MEDIUM';
export const LAYOUT_ID_2x3_ONE_PORTRAIT = 'LAYOUT_ID_2x3_ONE_PORTRAIT';
export const LAYOUT_ID_2x3_TWO_PORTRAIT = 'LAYOUT_ID_2x3_TWO_PORTRAIT';
export const LAYOUT_ID_2x3_TWO_LANDSCAPE = 'LAYOUT_ID_2x3_TWO_LANDSCAPE';
export const LAYOUT_ID_1x1_ONE = 'LAYOUT_ID_1x1_ONE';
export const LAYOUT_ID_1x1_TWO = 'LAYOUT_ID_1x1_TWO';

